language: go
sudo: required
go: 
  - 1.8.3
install: true

before_script:
  - mkdir -p $HOME/gopath/src/github.com/ServiceComb/go-chassis
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/ServiceComb/go-chassis/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/ServiceComb/go-chassis
  - cd $HOME/gopath/src/github.com/ServiceComb/go-chassis

jobs:
  include:
    - stage: Format Checker
      script: bash -x scripts/travis/formatChecker.sh
    - stage: DeadCode Checker
      script: 
        - go get -u github.com/tsenart/deadcode
        - bash -x scripts/travis/deadCodeChecker.sh
    -stage: GoConst Checker
      script:
        - go get -u github.com/jgautheron/goconst/cmd/goconst
        - bash -x scripts/travis/goConstChecker.sh
    - stage: Build
      script: 
        - go get github.com/FiloSottile/gvt
        - gvt restore
        - go build -o chassis
